# yazi.toml

[manager]
ratio = [0, 4, 0]

[opener]
# edit = [{ exec = 'zellij edit "$1"', desc = "Open File in a new pane" }]
edit = [{ run = 'zellij r -- nu -e "hx $1"', desc = "Open File in a new pane" }]

# [open]
# rules = [{ name = "*.nuon", use = ["text"] }]
